name: regionalhydroLSTM
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - matplotlib=3.8.4
  - pandas=2.2.2
  - numpy=1.26.4
  - tqdm=4.66.4
  - scipy=1.13.1
  - pytorch=2.3.0
  - scikit-learn=1.2.2
  - geopandas=0.14.4
  - rasterio=1.3.9
  - ipython=8.25.0
  - xarray=2024.5.0
